# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334ab8fbfa7710a7c04bc88dafe5a77573d9ee64b4f283da1715ee8856fe0688c552dfebab9cabbad2dcfff4659e7efada2791b82d8001d2dfa02147e423cda0

test:
  secret_key_base: 69b46de20e0a7ce8995b148f802add3ccb602516eb4f60ab93b71fa8fbc376596778c7e5f1f1b90849a13e99c8eb93f7a45e211e172521d6a588d39f402d302e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
